### ISSUE TITLE
Restart might end up with more instances than declared

### ISSUE THREAD

**Issue by goliatone** [goliatone/simple-process-manager#1]
We restart a process:

```
$ pm restart link.archive
Restarting worker "link.archive": PID 22743
```

If we list we see the workers seem to be restarted plus two new forked...

```
$ pm list                                         
name:      link.archive
worker:    ../workers/PersistenceWorker.js
instances: 2
pid:       22743
pids: 
  - 72734
  - 96179
  - 96180
  - 96181
```

Log output:

```
Restarting workers...
Terminating worker undefined
---> 72733 message: SIGINT
error TypeError: Cannot read property 'db' of undefined
    at Object.teardown (prj/node_modules/sails-mongo/lib/adapter.js:166:55)
    at prj/node_modules/waterline/lib/waterline.js:248:25
    at prj/node_modules/waterline/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (prj/node_modules/waterline/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (prj/node_modules/waterline/node_modules/async/lib/async.js:209:22)
    at module.exports.teardown (prj/node_modules/waterline/lib/waterline.js:242:9)
    at Promise (prj/workers/PersistenceWorker.js:62:17)
    at new Promise (<anonymous>)
    at PersistenceWorker.close (prj/workers/PersistenceWorker.js:57:16)
    at Object.close (prj/workers/PersistenceWorker.js:235:29)
    at process.on.event (../simple-process-manager/lib/worker.js:50:40)
    at process.emit (events.js:187:15)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
leader: child disconnected
Worker terminated...
Terminating worker undefined
---> 72734 message: SIGINT
worker exited with error code: 1
Ah! we should bring it back to life!
error TypeError: Cannot read property 'db' of undefined
    at Object.teardown (prj/node_modules/sails-mongo/lib/adapter.js:166:55)
    at prj/node_modules/waterline/lib/waterline.js:248:25
    at prj/node_modules/waterline/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (prj/node_modules/waterline/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (prj/node_modules/waterline/node_modules/async/lib/async.js:209:22)
    at module.exports.teardown (prj/node_modules/waterline/lib/waterline.js:242:9)
    at Promise (prj/workers/PersistenceWorker.js:62:17)
    at new Promise (<anonymous>)
    at PersistenceWorker.close (prj/workers/PersistenceWorker.js:57:16)
    at Object.close (prj/workers/PersistenceWorker.js:235:29)
    at process.on.event (../simple-process-manager/lib/worker.js:50:40)
    at process.emit (events.js:187:15)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
leader: child disconnected
Worker terminated...
worker exited with error code: 1
Ah! we should bring it back to life!
child: process 96180
child: process 96182
child: process 96181
child: process 96179
```

**Comment by goliatone** [comment]
```
(master)⚡ % pm list                                      

name:      link.archive
worker:    PersistenceWorker.js
instances: 2
pid:       13641
pids: 
  - 13642
  - 13643
(master)⚡ % pm restart link.archive                      
Restarting worker "link.archive": PID 13641
(master)⚡ % pm list                                      

name:      link.archive
worker:    PersistenceWorker.js
instances: 2
pid:       13641
pids: 
  - 17616
  - 22557
  - 22558
  - 22559
```
